### ISSUE TITLE
Tornado AsyncIOLoop monkey patch failing

### ISSUE THREAD

**Issue by mikedalpee** [urwid/urwid#344]
##### Description:
The Tornado  AsyncIOLoop  monkey patch does not work with Python 3.7.3, Tornado 6.02, urwid 2.0.1:
```
 Traceback (most recent call last):
  File "/home/mike/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/mike/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/mike/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/mike/pycharm-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/mike/Downloads/pubsub_demo/cli.py", line 107, in <module>
    main()
  File "/home/mike/Downloads/pubsub_demo/cli.py", line 80, in main
    terminal()
  File "/home/mike/Downloads/pubsub_demo/cli.py", line 54, in terminal
    event_loop=urwid.TornadoEventLoop(tornado.ioloop.IOLoop()))
  File "/home/mike/Downloads/pubsub_demo/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 1096, in __init__
    self._patch_poll_impl(ioloop)
  File "/home/mike/Downloads/pubsub_demo/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 1089, in _patch_poll_impl
    ioloop._impl = cls.PollProxy(ioloop._impl, idle_map)
AttributeError: 'AsyncIOLoop' object has no attribute '_impl'
```

##### Affected versions (if applicable)
- [ ] Latest stable version from `pypi`

##### Steps to reproduce (if applicable)

    event_loop=urwid.TornadoEventLoop(tornado.ioloop.IOLoop()))

##### Expected/actual outcome
no stack dump

**Comment by penguinolog** [comment]
Tornado support for version >=5 was merged in #537 and polishing in #541
For master branch issue is not more actual.
